### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;

### ISSUE THREAD

**Issue by ameersabith** [mwilliamson/java-mammoth#10]
I am new to mammoth and I followed your document to implement it. But application terminating with the error "java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;" .
I used `org.zwobble.mammoth:mammoth:1.4.0` dependency. 

My Java code is 

` DocumentConverter converter = new DocumentConverter();
        try {
            Result<String> result = converter.convertToHtml(new File(
                   Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),
                    "sample_doc.doc"));
            String html = result.getValue();
            Set<String> warning = result.getWarnings();
            webView.setWebViewClient(new WebViewClient());
            webView.loadUrl(html);
        } catch (IOException e) {
            e.printStackTrace();
        }`

Throwed exception is:

> AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.sparksupport.ameer.demoapplicaion, PID: 28784
                  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;
                      at org.zwobble.mammoth.internal.styles.StyleMapBuilder.<init>(StyleMapBuilder.java:25)
                      at org.zwobble.mammoth.internal.styles.StyleMap.<clinit>(StyleMap.java:36)
                      at org.zwobble.mammoth.internal.conversion.DocumentToHtmlOptions.<clinit>(DocumentToHtmlOptions.java:12)
                      at org.zwobble.mammoth.DocumentConverter.<init>(DocumentConverter.java:15)
                      at com.sparksupport.ameer.demoapplicaion.DocViewActivity.onCreate(DocViewActivity.java:34)
                      at android.app.Activity.performCreate(Activity.java:5966)
                   this   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2517)
                      at android.app.ActivityThread.access$800(ActivityThread.java:162)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:189)
                      at android.app.ActivityThread.main(ActivityThread.java:5529)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Optional" on path: DexPathList[[zip file "/data/app/com.sparksupport.ameer.demoapplicaion-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at org.zwobble.mammoth.internal.styles.StyleMapBuilder.<init>(StyleMapBuilder.java:25) 
                      at org.zwobble.mammoth.internal.styles.StyleMap.<clinit>(StyleMap.java:36) 
                      at org.zwobble.mammoth.internal.conversion.DocumentToHtmlOptions.<clinit>(DocumentToHtmlOptions.java:12) 
                      at org.zwobble.mammoth.DocumentConverter.<init>(DocumentConverter.java:15) 
                      at com.sparksupport.ameer.demoapplicaion.DocViewActivity.onCreate(DocViewActivity.java:34) 
                      at android.app.Activity.performCreate(Activity.java:5966) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2517) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:162) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
                      at android.os.Handler.dispatchMessage(Handler.java:106) 
                      at android.os.Looper.loop(Looper.java:189) 
                      at android.app.ActivityThread.main(ActivityThread.java:5529) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
                  	Suppressed: java.lang.ClassNotFoundException: java.util.Optional
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 19 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

Suggest me a solution

**Comment by mwilliamson** [comment]
Closing since this sounds like an issue with the platform rather than Mammoth.
